export const GET_RESOURCES = 'GET_RESOURCES';

export const CREATE_RESOURCE = 'CREATE_RESOURCE';
export const DELETE_RESOURCE = 'DELETE_RESOURCE';

export const CREATE_RESOURCE_FAIL = 'CREATE_RESOURCE_FAIL';
export const RESOURCES_LOADING = 'RESOURCES_LOADING';
export const GET_RESOURCES_FAIL = 'GET_RESOURCES_FAIL';

export const DELETE_RESOURCE_FAIL = 'DELETE_RESOURCE_FAIL';