export const GET_REVIEWS = 'GET_REVIEWS';
export const REVIEWS_LOADING = 'REVIEWS_LOADING';

export const CREATE_REVIEW = 'CREATE_REVIEW';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_FAIL = 'CREATE_QUIZ_FAIL';

export const UPDATE_REVIEW = 'UPDATE_REVIEW';
export const UPDATE_REVIEW_FAIL = 'UPDATE_REVIEW_FAIL';

export const DELETE_REVIEW = 'DELETE_REVIEW';
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL';
