export const GET_SCORES = 'GET_SCORES';
export const SCORES_LOADING = 'SCORES_LOADING';

export const CREATE_SCORE = 'CREATE_SCORE';
export const CREATE_SCORE_SUCCESS = 'CREATE_SCORE_SUCCESS';
export const CREATE_SCORE_FAIL = 'CREATE_QUIZ_FAIL';

export const UPDATE_SCORE = 'UPDATE_SCORE';
export const UPDATE_SCORE_FAIL = 'UPDATE_SCORE_FAIL';

export const DELETE_SCORE = 'DELETE_SCORE';
export const DELETE_SCORE_FAIL = 'DELETE_SCORE_FAIL';
